name: My Pipeline

on:
  push:
    branches:
    - main
jobs:
  MY_Jobs:
        name: deploying to docker
        runs-on:
        - ubuntu-latest
        steps:
          - name: Docker checkout code
            uses: actions/checkout@v4
          - name: Docker login
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.USERNAME_DOCKER }}
              password: ${{ secrets.PASSWORD_DOCKER }}
              
          - name: Build Docker Image
            run: docker build -t sairampandu/cicd .
          - name: push Docker image
            run: docker push sairampandu/cicd
          - name: Deploy to EC2
            uses: appleboy/ssh-action@v1.0.0
          
            with:
              username: ec2-user
              key: ${{ secrets.PRIVATE_KEY }}
              host: ${{ secrets.EC2_HOST }}
              
              script: |
                docker pull sairampandu/cicd
                docker stop app || true
                docker rm app || true
                docker run  -d -p 80:80 --name app sairampandu/cicd
              
    
    
